apiVersion: v1
kind: Service
metadata:
  namespace: p2-so1
  name: service-grpc
spec:
  ports:
  - name: grpc-client
    port: 5000
    targetPort: 5000
  selector:
    role: deployment-grpc
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  namespace: p2-so1
  name: service-rust
spec:
  ports:
  - name: rust-client
    port: 5003
    targetPort: 5003
  selector:
    role: deployment-rust
  type: LoadBalancer 