version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://db:27018/tarea2
  db:
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
