services:
  grpc_server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: KritianWhite/p2_grpc_server:latest
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      CLIENT_PORT: ${CLIENT_PORT}
    networks:
      - grpc_network

  grpc_client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: KritianWhite/p2_grpc_client:latest
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      SERVER_PORT:  ${SERVER_PORT}
      CLIENT_HOST:  ${CLIENT_HOST}
      CLIENT_PORT:  ${CLIENT_PORT}
      KAFKA_BROKER: ${KAFKA_BROKER}
      KAFKA_TOPIC:  ${KAFKA_TOPIC}
    networks:
      - grpc_network

networks:
  grpc_network: