version: '3'
services:
  p1_so1_backend:
    build:
      context: ./backend
    image: kritianwhite/proyecto1-p1_so1_backend
    container_name: p1_so1_backend
    ports:
      - "5000:5000"
    depends_on:
      - p1_so1_mysqldb
    networks:
      - app_net
    restart: always
    privileged: true
    pid: host
    volumes:
      - /proc:/proc
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=${SERVER_PORT}

  p1_so1_frontend:
    build:
      context: ./frontend
    image: kritianwhite/proyecto1-p1_so1_frontend
    container_name: p1_so1_frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app_net
    depends_on:
      - p1_so1_backend

  p1_so1_mysqldb:
    restart: on-failure
    container_name: p1_so1_mysqldb
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - app_net
    volumes:
      - p1-so1-mysql-vol:/var/lib/mysql
      - ./database_init.sql:/docker-entrypoint-initdb.d/database_init.sql

networks:
    app_net:
      driver: bridge

volumes:
  p1-so1-mysql-vol: