CREATE DATABASE IF NOT EXISTS p1_so1_bd;

CREATE TABLE IF NOT EXISTS TASK (
	ID_TASK INT PRIMARY KEY AUTO_INCREMENT, 
	PID INT,
	NOMBRE VARCHAR(255),
	ESTADO INT,
	RSS INT,
	UID INT,
	RAM INT,
	TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CHILD_TASK (
	ID_CHILD_TASK INT PRIMARY KEY AUTO_INCREMENT,
	ID_TASK INT,
	PID INT,
	NOMBRE VARCHAR(255),
	ESTADO INT,
	RSS INT,
	UID INT,
	TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ID_TASK) REFERENCES TASK (ID_TASK)
);


CREATE TABLE IF NOT EXISTS RAM (
	ID_RAM INT PRIMARY KEY AUTO_INCREMENT,
	TOTAL_MEMORIA FLOAT,
	MEMORIA_LIBRE FLOAT,
	MEMORIA_UTILIZADA FLOAT,
	PORCENTAJE_UTILIZADO FLOAT,
	TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CPU (
	ID_CPU INT PRIMARY KEY AUTO_INCREMENT,
	CPU_TOTAL FLOAT,
	CPU_PORCENTAJE FLOAT,
	CPU_PERCENTAGE FLOAT,
	RUNNING INT,
	SLEEPING INT,
	ZOMBIE INT,
	STOPPED INT,
	TOTAL INT,
	TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);